inventory_management_system/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using inventory_management_system.Models;

namespace inventory_management_system.Controllers
{
    public class DefaultController : Controller
    {
        // GET: Default
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }

        orderhistoryimpelement ohi = new orderhistoryimpelement();
        public ActionResult OrderedHistory(string username)
        {

            if (Session["username"] == null)
            {
                return RedirectToAction("Login", "Account");
            }
            else
            {
                ViewBag.username = username;
                ModelState.Clear();
                return View(ohi.GetOrder());
                //return View();
            }
            
        }

        public ActionResult Add()
        {
            return View();
        }

        public ActionResult Report()
        {
            return View();
        }
        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            Session.Abandon();
            return RedirectToAction("Login", "Account");
        }
    }
}

inventory_management_system/Controllers/EmpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using inventory_management_system.Models;




namespace inventory_management_system.Controllers
{
    public class EmpController : Controller
    {
        CrudImplementation ci = new CrudImplementation();
        public ActionResult Add()
        {
            ModelState.Clear();
            return View(ci.GetEmp());
        }

        // GET: Emp/Details/5
        public ActionResult Details(int id)
        {
            return View(ci.GetEmp().Find(itemodel => itemodel.prod_Id == id));
        }

        // GET: Emp/Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Emp/Create
        [HttpPost]
        public ActionResult Create(CrudProp empinsert)
        {
            try
            {
                // TODO: Add insert logic here
                if (ModelState.IsValid)
                {
                    if (ci.insertemp(empinsert))
                    {
                        ViewBag.message = "The Product you record is successfully saved!";
                        ModelState.Clear();
                    }

                }

                return RedirectToAction("Add");
            }
            catch
            {
                return View();
            }
        }

        // GET: Emp/Edit/5
        public ActionResult Edit(int id)
        {
            return View(ci.GetEmp().Find(itemodel => itemodel.prod_Id == id));
        }

        // POST: Emp/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, CrudProp updateemp)
        {
            try
            {
                // TODO: Add update logic here
                ci.editemp(updateemp);
                return RedirectToAction("Add");
            }
            catch
            {
                return View();
            }
        }

        // GET: Emp/Delete/5
        [HttpGet]
        public ActionResult Delete(int id)
        {
            ci.deleteemp(id);
            return RedirectToAction("Add");
        }

        // POST: Emp/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Add");
            }
            catch
            {
                return View();
            }
        }
    }
}

inventory_management_system/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/a7e3800dc5.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

    @*<link href="~/StyleSheet.css" rel="stylesheet" />*@

    

    @*side-navbar-script*@
    <script>
        /* Set the width of the side navigation to 250px and the left margin of the page content to 250px */
        function openNav() {
          document.getElementById("mySidenav").style.width = "250px";
          document.getElementById("main").style.marginLeft = "250px";
        }

        /* Set the width of the side navigation to 0 and the left margin of the page content to 0 */
        function closeNav() {
          document.getElementById("mySidenav").style.width = "0";
          document.getElementById("main").style.marginLeft = "0";
        }
    </script>

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">VAPESTER</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <center><i class="fa-solid fa-house"></i>&nbsp;&nbsp;@Html.ActionLink("Home", "Index", "Default")<span class="sr-only">(current)</span></center>
                </li>
                &nbsp;&nbsp;&nbsp;&nbsp;
                <li class="nav-item">
                    <i class="fa-solid fa-box"></i>&nbsp;&nbsp;@Html.ActionLink("Products", "Add", "Emp")
                </li>
                &nbsp;&nbsp;&nbsp;&nbsp;
                <li class="nav-item">
                    <i class="fa-solid fa-clock"></i>&nbsp;&nbsp;@Html.ActionLink("Transaction", "OrderedHistory", "Default")
                </li>
                &nbsp;&nbsp;&nbsp;&nbsp;
                <li class="nav-item">
                    <i class="fa-solid fa-chart-simple"></i>&nbsp;&nbsp;@Html.ActionLink("Sales", "Index", "Sales")
                </li>
                &nbsp;&nbsp;&nbsp;&nbsp;
                <li class="nav-item">
                    <i class="fa-solid fa-users"></i>&nbsp;&nbsp;@Html.ActionLink("Employee", "Teller", "Account")
                </li>
                &nbsp;&nbsp;&nbsp;&nbsp;
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown">
                        <i class="fa-solid fa-user-plus"></i>&nbsp;&nbsp;Create an Account
                    </a>
                    <div class="dropdown-menu">
                        <center><i class="fa-sharp fa-solid fa-user-tie"></i>&nbsp;&nbsp;@Html.ActionLink("Admin", "CreateAdmin", "Account")</center><br />
                        <center><i class="fa-solid fa-users-line"></i>&nbsp;&nbsp;@Html.ActionLink("Teller", "Create", "Account")</center>
                        <div class="dropdown-divider"></div>
                    </div>
                </li>
                
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <i class="fa-solid fa-right-from-bracket"></i>&nbsp;&nbsp;@Html.ActionLink("Logout", "LogOut", "Default")<span class="sr-only">(current)</span>
                </li>
            </ul>
        </div>
    </nav>
    <div class="row">
        <div class="col-12">
            <div class="container body-content">
                @RenderBody()
                <hr />
                <footer>
                    <p>© &copy; @DateTime.Now.Year Vapester. All Rights Reserved.</p>
                </footer>
            </div>
        </div>
    </div>
    
    
</body>
</html>